import NavBar from "./components/NavBar/NavBar";
import { ContextContainer } from "./context-container";
import favicon from "../../public/Fv01.png";
import Head from "next/head"
import "./globals.css";
import Footer from "./components/Footer/Footer";

export const metadata = {
  title: "Fernandez Voley",
  description: "Generated by create next app",
  image: favicon,
};

// export const getData=async ()=>{
//   const client=new QueryClient()
//   // await client.prefetchQuery([""],)
//   return desydrate(client)
// }

export default async function RootLayout({ children }) {
  // const state= await getData()

  return (
    <html lang="es" className='scroll-smooth' >
      <Head>
        <link rel="shortcut icon" href="/favicon.ico" />
	</Head>
      <body className="scroll-smooth bg-gradient-to-tr from-cyan-900 via-cyan-800 to-orange-700 overflow-x-hidden selection:bg-orange-500/20">
        <ContextContainer>
          <NavBar />
          {children}
          <Footer/>
        </ContextContainer>
      </body>
    </html>
  );
}
