import { QueryClient, desydrate } from "@tanstack/react-query";
import NavBar from "./components/NavBar/NavBar";
import { ContextContainer } from "./context-container";
import "./globals.css";

export const metadata = {
  title: "Fernandez Voley",
  description: "Generated by create next app",
};

// export const getData=async ()=>{
//   const client=new QueryClient()
//   // await client.prefetchQuery([""],)
//   return desydrate(client)
// }

export default async function RootLayout({ children }) {
  // const state= await getData()

  return (
    <html lang="es">
      <body>
        <ContextContainer>
          <NavBar />
          {children}
        </ContextContainer>
      </body>
    </html>
  );
}
